---
- name: install packages
  hosts: local
  vars:
    PACKAGE_LIST:
      - nginx
      - mysql
      - nodejs
  tasks:
    - name: install the listed packages
      ansible.builtin.package:
        name: "{{ ITEM }}"
        state: present
      loop: "{{ PACKAGE_LIST }}"
      when: ansible_os_family == "RedHat"
