---
- name: install packages
  hosts: local
  become: true
  vars:
    PACKAGE_LIST:
      - nginx
      - mysql
      - nodejs
  tasks:
    - name: install the listed packages
      ansible.builtin.package:
        name: "{{ PACKAGE_LIST }}"
        state: present
      when: ansible_os_family == "RedHat" 
